name = "blog-microservice"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

[observability.logs]
enabled = true
invocation_logs = true
persist = true

[vars]
ALLOWED_ORIGIN = "https://www.neuralcook.com"

# OpenTelemetry Exporter Endpoint (e.g. Grafana Cloud OTLP Gateway)
# The Headers/API Key must be set via `wrangler secret put OTEL_EXPORTER_OTLP_HEADERS`
OTEL_EXPORTER_OTLP_ENDPOINT = ""
