export const siteMetadata = {
  title: "VIKI",
  author: "Vikramaditya Singh",
  designation: "Software engineer III",
  company: "Oracle",
  headerTitle: "NEURAL COOK",
  description: "A posts created with Next.js and Tailwind.css",
  language: "en-us",
  theme: "system", // system, dark or light
  siteUrl: "",
  siteRepo: "",
  siteLogo: "/static/images/logo.png",
  image: "/static/images/logo.png",
  socialBanner: "/static/images/twitter-card.jpg",
  email: "vikramaditya.bhadoria@gmail.com",
  github: "https://github.com/Vikramadtya",
  twitter: "https://twitter.com/Twitter",
  facebook: "https://facebook.com",
  youtube: "https://youtube.com",
  linkedin: "https://www.linkedin.com/in/vikrmadityasngh/",
  instagram: "https://www.instagram.com/blissfullvibes101",
  locale: "en-US",
  hostname: "www.neuralcook.com",
  analytics: {
    umamiSrcSrcipt: "https://eu.umami.is/script.js",
    umamiWebsiteId: "2d0c15ba-afa2-4213-960b-763c2285f1ee",
  },
  analyticsURL: "https://eu.umami.is/share/kzVVpxmlV8WbabaH/something.com",
  postDateTemplate: {
    year: "numeric",
    month: "long",
    day: "numeric",
  },
  githubRawEndpoint:
    "https://raw.githubusercontent.com/Vikramadtya/Blog/refs/heads/main/blog-datastore/blogs/",
  apiBaseUrl: "https://www.neuralcook.com",
  portfolioLink: "https://www.vikramaditya-singh.in",
  openToWork: true,
  giscus: {
    label: "comments",
    commentsRepo: "Vikramadtya/Blog-Scratch",
    commentsRepoId: "R_kgDOM061bQ",
    commentsMapping: "pathname",
    gitHubDiscussionCategory: "Announcements",
    gitHubDiscussionCategoryId: "DIC_kwDOM061bc4Ciqd1",
    emitMetadata: "0",
    strict: "0",
    lightTheme: "noborder_light",
    darkTheme: "noborder_dark",
    reactionsEnabled: "1",
    inputPosition: "top",
    lang: "en",
    loading: "lazy",
  },
};
